## configuration
##

kubernetes:
  namespace: default

ingress:
  hostname: test_web_app.example.com

application:
  name: test_web_app
  image:
    repository: myrepository
    tag: 1.0.0
    pullPolicy: IfNotPresent

  # Number of pods to create.
  replicas: 3
