kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "application.name" . }}-deployment
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    app: {{ template "application.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        name: {{ template "application.name" . }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ template "application.name" . }}
        image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag }}"
        imagePullPolicy: "{{ .Values.application.image.pullPolicy }}"
    replicas: {{ .Values.application.replicas }}
