## configuration
##

kubernetes:
  namespace: default

ingress:
  hostname: test-web-app.example.com

application:
  name: test-web-app
  image:
    repository: adyromantika/test-web-app
    tag: %TAG%
    pullPolicy: IfNotPresent

  # Number of pods to create.
  replicas: 3
